// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace DeltaRelationshipModelML.Model
{
    public class ModelInput
    {
        [ColumnName("ExpInt"), LoadColumn(0)]
        public bool ExpInt { get; set; }


        [ColumnName("FrndAgr"), LoadColumn(1)]
        public bool FrndAgr { get; set; }


        [ColumnName("SnInsn"), LoadColumn(2)]
        public bool SnInsn { get; set; }


        [ColumnName("BrvAfr"), LoadColumn(3)]
        public bool BrvAfr { get; set; }


        [ColumnName("Npc12Rel"), LoadColumn(4)]
        public float Npc12Rel { get; set; }


        [ColumnName("Npc2RelIncr"), LoadColumn(5)]
        public float Npc2RelIncr { get; set; }


        [ColumnName("DeltaRel"), LoadColumn(6)]
        public float DeltaRel { get; set; }

        public ModelInput(bool[] character, float npcRel, float playerNpc2RelIncr)
        {
            ExpInt = character[0];
            FrndAgr = character[1];
            SnInsn = character[2];
            BrvAfr = character[3];

            Npc12Rel = npcRel;
            Npc2RelIncr = playerNpc2RelIncr;
        }
    }
}
