// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace InitialRelationshipModelML.Model
{
    public class ModelInput
    {
        [ColumnName("ExtInt1"), LoadColumn(0)]
        public bool ExtInt1 { get; set; }


        [ColumnName("FrndAgr1"), LoadColumn(1)]
        public bool FrndAgr1 { get; set; }


        [ColumnName("SnInsn1"), LoadColumn(2)]
        public bool SnInsn1 { get; set; }


        [ColumnName("BrvAfr1"), LoadColumn(3)]
        public bool BrvAfr1 { get; set; }


        [ColumnName("ExtInt2"), LoadColumn(4)]
        public bool ExtInt2 { get; set; }


        [ColumnName("FrndAgr2"), LoadColumn(5)]
        public bool FrndAgr2 { get; set; }


        [ColumnName("SnInsn2"), LoadColumn(6)]
        public bool SnInsn2 { get; set; }


        [ColumnName("BrvAfr2"), LoadColumn(7)]
        public bool BrvAfr2 { get; set; }


        [ColumnName("InitRel"), LoadColumn(8)]
        public float InitRel { get; set; }

        public ModelInput(bool[] inputData)
        {
            ExtInt1 = inputData[0];
            FrndAgr1 = inputData[1];
            SnInsn1 = inputData[2];
            BrvAfr1 = inputData[3];
            ExtInt2 = inputData[4];
            FrndAgr2 = inputData[5];
            SnInsn2 = inputData[6];
            BrvAfr2 = inputData[7];
        }
    }
}
